name: routefinding
description: A new Flutter project.
publish_to: 'none'
version: 1.2.3+39

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_app_check: ^0.3.2+7
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^17.0.0

  shared_preferences: ^2.2.2
  package_info_plus: ^8.3.0

  http: ^0.13.0


  # Media
  video_player: ^2.9.5
  image_picker: ^0.8.7+3

  # (선택) 캐시된 네트워크 이미지 로딩
  cached_network_image: ^3.2.3
  photo_view: ^0.14.0

  # Intl
  intl: ^0.20.2

  # Maps & clustering
  url_launcher: ^6.2.5
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.12.1
  google_maps_cluster_manager:
    git:
      url: https://github.com/bpillon/google_maps_cluster_manager.git
      ref: master


  # Geolocation / permissions
  geocoding: ^2.0.5
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1


  # Geohash
  dart_geohash: ^2.1.0

  # 기타
  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  app_badger: ^0.0.2
  gpx: ^2.3.0
  share_plus: ^11.0.0
  path_provider: ^2.1.2
  # flutter_windowmanager: ^0.2.0
  google_mobile_ads: ^5.0.0
  smooth_page_indicator: ^1.1.0
  reorderables: ^0.6.0
  file_picker: ^10.2.0
  fl_chart: ^0.68.0




flutter:
  uses-material-design: true

  assets:
    - assets/icons/cluster_icon.png
    - assets/icons/lead_marker.png
    - assets/icons/bouldering_marker.png
    - assets/videos/splash_video.mp4
    - assets/default_profile.png
    - assets/icons/arrow_marker.png
    - assets/crown_full.png
    - assets/crown_min.png
    - assets/crown_low.png

dev_dependencies:
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  # Android/iOS 모두 변경
  android: true
  ios: true

  # 이 파일 하나만 있으면, background와 foreground 모두 동일하게 써 줌 → 풀 블리드 아이콘으로 활용
  image_path: "assets/icons/app_icon.png"

  # adaptive 아이콘용으로 foreground/background 명시 가능
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  adaptive_icon_background: "assets/icons/app_icon.png"
