buildscript {
    repositories {
        google()
        mavenCentral()
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// 커스텀 빌드 디렉토리 설정
def newBuildDir = file("${rootDir}/../build")
buildDir = newBuildDir

subprojects {
    buildDir = new File(newBuildDir, project.name)
    evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
