//firebase_options.dart

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYVsosvdSKaUB7ekO-NKzSdCX1O4X0-sw',
    appId: '1:602187162553:web:144d79bea5b1834dc70c68',
    messagingSenderId: '602187162553',
    projectId: 'routefinding09-4b597',
    authDomain: 'routefinding09-4b597.firebaseapp.com',
    storageBucket: 'routefinding09-4b597.firebasestorage.app',
    measurementId: 'G-XWFMDFHFL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIG_y0ZfuX-wlnKoviZj85AZsAHoMKieQ',
    appId: '1:602187162553:android:e584eebfc03395adc70c68',
    messagingSenderId: '602187162553',
    projectId: 'routefinding09-4b597',
    storageBucket: 'routefinding09-4b597.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0NX7OJtYLIH5Lnnyj7QBbmU185SOvHDs',
    appId: '1:602187162553:ios:2dbbd841254eef89c70c68',
    messagingSenderId: '602187162553',
    projectId: 'routefinding09-4b597',
    storageBucket: 'routefinding09-4b597.firebasestorage.app',
    iosBundleId: 'com.yusungyun.RouteFinding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0NX7OJtYLIH5Lnnyj7QBbmU185SOvHDs',
    appId: '1:602187162553:ios:f6e4aa154f4f17c3c70c68',
    messagingSenderId: '602187162553',
    projectId: 'routefinding09-4b597',
    storageBucket: 'routefinding09-4b597.firebasestorage.app',
    iosBundleId: 'com.example.routefinding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8OUdHJ-ra-5ofJ0cHiKtZYoYKB1URf6U',
    appId: '1:602187162553:web:54cc7c332fb38e9bc70c68',
    messagingSenderId: '602187162553',
    projectId: 'routefinding09-4b597',
    authDomain: 'routefinding09-4b597.firebaseapp.com',
    storageBucket: 'routefinding09-4b597.appspot.com',
    measurementId: 'G-VVRZ67MJCY',
  );

}
